### ISSUE TITLE
feature: Add custom header for dio client

### ISSUE THREAD

**Issue by castletaste** [LiWenHui96/upgrade_util#2]
**Description**

There is no option to add custom header 

**Desired Solution**

it would be awesome to have a custom header for dio client

**Additional Context**

There are cases where an apk file should only be accessible only by token, for security reasons

**Comment by LiWenHui96** [comment]
@castletaste 使用 [2.3.0](https://pub.dev/packages/upgrade_util/versions/2.3.0) ，采用 `downloadUri`, `saveName`, `downloadInterceptors`, `deleteOnError`, `lengthHeader`, `data`, `options` 这些字段对 `dio` 进行粉饰。

**Comment by LiWenHui96** [comment]
v2.3.0 已发布，功能完成，并关闭issus。
